import { Plus, Trash2 } from "lucide-react";
import { useState } from "react";
import PageControls, { REVIEW_PAGE_SIZE } from "./PageControls";

export default function MeetingMinutes({ output, onEdit, busy, Textarea }) {
  const [requestedPage, setPage] = useState(0);
  const page = Math.min(requestedPage, Math.max(0, Math.ceil((output.minutes?.length || 0) / REVIEW_PAGE_SIZE) - 1));
  const editRow = (index, key, value) => onEdit((current) => ({ ...current, minutes: (current.minutes || []).map((row, i) => i === index ? { ...row, [key]: value } : row) }));
  return <div className="summary-panel">
    <label className="field"><span>Meeting summary</span><Textarea value={output.summary} rows={4} maxLength={12000} disabled={busy} onChange={(event) => onEdit((current) => ({ ...current, summary: event.target.value }))} /></label>
    <div className="minutes-heading"><h2>Minutes of meeting</h2><button className="button subtle" disabled={busy || (output.minutes || []).length >= 2000} onClick={() => { setPage(Math.floor((output.minutes?.length || 0) / REVIEW_PAGE_SIZE)); onEdit((current) => ({ ...current, minutes: [...(current.minutes || []), { topic: "", discussion: "", outcome: "" }] })); }}><Plus size={16} />Add topic</button></div>
    {(output.minutes || []).slice(page * REVIEW_PAGE_SIZE, (page + 1) * REVIEW_PAGE_SIZE).map((row, pageIndex) => { const index = pageIndex + page * REVIEW_PAGE_SIZE; return <article className="minute-row" key={index}><span className="question-number">{String(index + 1).padStart(2, "0")}</span><div><input className="topic-title" aria-label={"Topic " + (index + 1)} value={row.topic} maxLength={180} placeholder="Topic" disabled={busy} onChange={(event) => editRow(index, "topic", event.target.value)} /><Textarea aria-label={"Discussion " + (index + 1)} rows={3} maxLength={1800} value={row.discussion} disabled={busy} onChange={(event) => editRow(index, "discussion", event.target.value)} /><label className="field"><span>Outcome</span><Textarea aria-label={"Outcome " + (index + 1)} rows={2} maxLength={600} placeholder="Agreed outcome or unresolved point" value={row.outcome} disabled={busy} onChange={(event) => editRow(index, "outcome", event.target.value)} /></label></div><button className="icon-button" aria-label={"Remove topic " + (index + 1)} title="Remove topic" disabled={busy} onClick={() => onEdit((current) => ({ ...current, minutes: current.minutes.filter((_, i) => i !== index) }))}><Trash2 size={16} /></button></article>; })}
    <PageControls count={output.minutes?.length || 0} page={page} onChange={setPage} label="topics" busy={busy} />
    {!output.minutes?.length && <p className="section-description">No topic-by-topic minutes in this saved version.</p>}
    <div className="two-columns">{[["decisions", "Decisions"], ["blockers", "Blockers"], ["open_questions", "Open questions / awaiting confirmation"]].map(([key, label]) => <section key={key}><div className="minutes-heading"><h2>{label}</h2><button className="icon-button" disabled={busy || (output[key] || []).length >= 2000} title={"Add to " + label} aria-label={"Add to " + label} onClick={() => onEdit((current) => ({ ...current, [key]: [...(current[key] || []), ""] }))}><Plus size={16} /></button></div>{output[key]?.length ? output[key].map((text, index) => <div className="editable-line" key={index}><Textarea aria-label={label + " " + (index + 1)} value={text} maxLength={600} rows={2} disabled={busy} onChange={(event) => onEdit((current) => ({ ...current, [key]: current[key].map((item, i) => i === index ? event.target.value : item) }))} /><button className="icon-button" aria-label={"Remove " + label + " " + (index + 1)} title="Remove" disabled={busy} onClick={() => onEdit((current) => ({ ...current, [key]: current[key].filter((_, i) => i !== index) }))}><Trash2 size={14} /></button></div>) : <p>None recorded.</p>}</section>)}</div>
  </div>;
}
