import { ArrowRight, Check, ClipboardCheck, LockKeyhole } from "lucide-react";
import { PLANS, formatINR } from "../lib/plans";

export default function PricingContent({ onBack }) {
  return <section className="pricing-content">
    <div className="section-heading"><div><p className="eyebrow">Kaarya plans</p><h1>Accountability, at your scale.</h1><p className="section-description">Monthly prices in INR, plus applicable taxes.</p></div>{onBack && <button className="button" onClick={onBack}>Workspace<ArrowRight size={16} /></button>}</div>
    <div className="pricing-grid">{Object.values(PLANS).map((plan) => <article className={"plan-item " + (plan.id === "pro" ? "featured" : "")} key={plan.id}>
      <div className="plan-heading"><h2>{plan.name}</h2><span className="badge">{plan.id === "free" ? "Available" : plan.id === "pro" ? "Checkout coming soon" : "Planned"}</span></div>
      <p className="plan-price">{formatINR(plan.price)}<span>/ month</span></p>
      <ul>{[`${plan.meetings} meeting${plan.meetings > 1 ? "s" : ""} per ${plan.period}${plan.id === "team" ? ", pooled" : ""}`, `${plan.retained.toLocaleString("en-IN")} retained meetings`, `${plan.seats} organizer${plan.seats > 1 ? "s" : ""}`, `${plan.inputCharacters.toLocaleString("en-IN")} characters per meeting`, "Review, copy, export and stakeholder updates"].map((item) => <li key={item}><Check size={16} /><span>{item}</span></li>)}</ul>
      <p className="usage-detail">{plan.id === "free" ? "One AI refinement per meeting, up to one per day. No card required." : plan.id === "pro" ? "Two AI refinements per meeting, up to 80 per month. Personal history and flexible daily usage." : "Workspace roles, shared preparation and team invitations are in development."}</p>
      {plan.id === "free" ? <a className="button primary" href="/">Open workspace<ArrowRight size={16} /></a> : <p className="plan-availability"><LockKeyhole size={15} />Not accepting payments yet</p>}
    </article>)}</div>
    <section className="positioning-band"><ClipboardCheck size={25} /><div><h2>Why Kaarya instead of another chat?</h2><p>For a one-off summary, a general AI chat can be enough. Choose Kaarya when the work continues after the answer: approved actions, named owners, update links and a meeting history you can return to.</p><p>The product we are building connects each commitment to its source, its latest update and the next meeting's preparation. Historical briefs and automated nudges are the next release, not features being charged for today.</p></div></section>
    <div className="pricing-faq"><h2>Clear limits. No surprise deletion.</h2><details><summary>What happens after five Free meetings?</summary><p>Drafts count toward the five-meeting limit. You can export and deliberately delete a meeting to make room. Nothing is removed automatically. Deletion does not restore the day's generation allowance.</p></details><details><summary>What uses a meeting allowance?</summary><p>A successfully generated draft counts, even if it has no action items. Failed processing and the example do not count. Manual edits, reading, exports and stakeholder status updates do not use meeting credits.</p></details><details><summary>Are recordings included?</summary><p>The current workspace supports 30-second voice notes. Full meeting recording and unlimited transcription are not included.</p></details><details><summary>Will I be charged now?</summary><p>No. Paid plans will open after payment verification, renewal and cancellation testing. Your account stays Free until you explicitly purchase an available plan.</p></details></div>
  </section>;
}
